version: '3'
services:
  challenge-payment-api:
    container_name: challenge-payment-api
    image: challenge-payment-api
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    networks:
      - global-default
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      #POSTGRES_DB: localstack
    ports:
      - 5432:5432
    networks:
      - global-default
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 5050:80
      - 5051:443
    depends_on:
      - postgres
networks:
  global-default:
    external: true
      
